## Skip Connection
----

## Полезные ссылки:
https://habr.com/ru/articles/688350/

Concatenate layer -- проверить
Average layer -- проверить
Maximum layer -- проверить
Minimum layer -- проверить
Add layer -- проверить
Subtract layer -- проверить
Multiply layer -- проверить
Dot layer -- минус.

In [3]:
import tensorflow as tf
import numpy as np

----
## Concatenate

На вход принимает список слоёв с одинаковым shape, кроме одного(будет указан в axis)
Возвращает объединённый tensor, состоящий из входных слоёв.
Помогает вообще не терять фичи, а просто переносит их с одного места на другое. 

In [4]:
x = np.arange(10).reshape(5, 2)
y = np.arange(10, 25).reshape(5, 3)
print(x)
print(y)
res = tf.keras.layers.Concatenate(axis=1)([x, y])
print(res)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]
tf.Tensor(
[[ 0  1 10 11 12]
 [ 2  3 13 14 15]
 [ 4  5 16 17 18]
 [ 6  7 19 20 21]
 [ 8  9 22 23 24]], shape=(5, 5), dtype=int64)


----
## Average
Принимает слои с идентичной формой и хранит **среднее арифметическое** соответственных нейронов каждого слоя


In [5]:
x = np.ones(4).reshape(2, 2)
y = np.zeros(4).reshape(2, 2)
print(x)
print(y)
res = tf.keras.layers.Average()([x, y])
print(res)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
tf.Tensor(
[[0.5 0.5]
 [0.5 0.5]], shape=(2, 2), dtype=float32)


----
## Maximum
Принимает слои с идентичной формой и хранит **наибольший** из нейронов на каждой позиции

In [8]:
x = np.array([[1, 5], [4, 8]])
y = np.array([[2, 3], [7, 6]])
print(x)
print(y)
res = tf.keras.layers.Maximum()([x, y])
print(res)

[[1 5]
 [4 8]]
[[2 3]
 [7 6]]
tf.Tensor(
[[2 5]
 [7 8]], shape=(2, 2), dtype=int64)


----
## Minimum
Принимает слои с идентичной формой и хранит **наименьший** из нейронов на каждой позиции

In [9]:
x = np.array([[1, 5], [4, 8]])
y = np.array([[2, 3], [7, 6]])
print(x)
print(y)
res = tf.keras.layers.Minimum()([x, y])
print(res)

[[1 5]
 [4 8]]
[[2 3]
 [7 6]]
tf.Tensor(
[[1 3]
 [4 6]], shape=(2, 2), dtype=int64)


----
## Add
Принимает слои с идентичной формой и возвращает поэлементную **сумму** значений нейронов на соответствующих местах

In [10]:
x = np.arange(4).reshape(2, 2)
y = np.arange(4, 8).reshape(2, 2)
print(x)
print(y)
res = tf.keras.layers.Add()([x, y])
print(res)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
tf.Tensor(
[[ 4  6]
 [ 8 10]], shape=(2, 2), dtype=int64)


----
## Subtract
Принимает слои с идентичной формой и возвращает поэлементную **разность** значений нейронов на соответствующих местах

In [11]:
x = np.arange(4, 8).reshape(2, 2)
y = np.arange(4).reshape(2, 2)
print(x)
print(y)
res = tf.keras.layers.Subtract()([x, y])
print(res)

[[4 5]
 [6 7]]
[[0 1]
 [2 3]]
tf.Tensor(
[[4 4]
 [4 4]], shape=(2, 2), dtype=int64)


----
## Multiply
Принимает слои с идентичной формой и возвращает поэлементное **перемножение** значений нейронов на соответствующих местах

In [12]:
x = np.arange(4).reshape(2, 2)
y = np.arange(4, 8).reshape(2, 2)
print(x)
print(y)
res = tf.keras.layers.Multiply()([x, y])
print(res)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
tf.Tensor(
[[ 0  5]
 [12 21]], shape=(2, 2), dtype=int64)


----
## Dot
Перемножает нейроны слоёв как **матрицы**

In [18]:
x = np.arange(10).reshape(1, 5, 2)
y = np.arange(10, 20).reshape(1, 2, 5)
print(x)
print(y)
res = tf.keras.layers.Dot(axes=(1, 2))([x, y])
print(res)

[[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]]
[[[10 11 12 13 14]
  [15 16 17 18 19]]]
tf.Tensor(
[[[260 360]
  [320 445]]], shape=(1, 2, 2), dtype=int64)


Импорт библиотек

In [3]:
!pip install livelossplot

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
%cd drive/MyDrive/project/YaMlProject
%ls

/content/drive/MyDrive/project/YaMlProject
core/  data/  models/  notebooks/  README.md  requirements.txt


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import numpy as np
from PIL import Image
import tensorflow as tf
import torchvision as tv
from livelossplot import PlotLossesKeras
import matplotlib.pyplot as plt

from core.datasets import get_ds

In [17]:
train_ds, val_ds, test_ds = get_ds('repaired_data_train', 'repaired_data_test', back=0)

In [18]:
model = tf.keras.Sequential([
    tf.keras.Input(shape=(32, 32, 3), batch_size=512),
    tf.keras.layers.Conv2D(32, kernel_size=5, activation='relu'),
    tf.keras.layers.AveragePooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.AveragePooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, kernel_size=5, activation='relu'),
    tf.keras.layers.AveragePooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax'),
])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_10 (Conv2D)          (512, 28, 28, 32)         2432      
                                                                 
 average_pooling2d_8 (Averag  (512, 14, 14, 32)        0         
 ePooling2D)                                                     
                                                                 
 conv2d_11 (Conv2D)          (512, 12, 12, 64)         18496     
                                                                 
 batch_normalization_3 (Batc  (512, 12, 12, 64)        256       
 hNormalization)                                                 
                                                                 
 average_pooling2d_9 (Averag  (512, 6, 6, 64)          0         
 ePooling2D)                                                     
                                                      

In [19]:
model.compile(optimizer='adam', metrics=['accuracy'],
        loss=tf.keras.losses.SparseCategoricalCrossentropy())

In [21]:
model.fit(train_ds, validation_data=val_ds, epochs=50,
          callbacks=[PlotLossesKeras()], verbose=False)

KeyboardInterrupt: ignored