In [88]:
import pickle
import numpy as np
import pandas as pd

In [89]:
pred_s6 = pickle.load(open('../checkpoint_answers/model_s_6_avg_f1_score.h5', 'rb'))
pred_g11 = pickle.load(open('../checkpoint_answers/model_g_11_avg_f1_score.h5', 'rb'))

In [90]:
ovas = []
for i in ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine']:
    ovas.append(pickle.load(open(f'../checkpoint_answers/model_{i}_avg_categorical_accuracy.h5', 'rb')))
ovas = np.column_stack(ovas)
ovas.shape

(25000, 10)

In [91]:
ans = (pred_s6 + pred_g11) / 2

In [92]:
# ensemble_model_name = 'ensemble_g_7_all'
# ans = pd.DataFrame({'Id': np.arange(ans.shape[0]), 'Category': ans})
# ans.to_csv(f'../answers/{ensemble_model_name}.csv', index=False)

In [93]:
for i in range(10):
    ans1 = ans.copy()
    ans1[:, i] = ovas[:, i]
    ans1 = np.argmax(ans1, axis=-1)
    ensemble_model_name = f'ensemble_g_7_{i}'
    ans_file = pd.DataFrame({'Id': np.arange(ans1.shape[0]), 'Category': ans1})
    ans_file.to_csv(f'../answers/{ensemble_model_name}.csv', index=False)

In [94]:
def f(x):
    return sorted(map(lambda x: (x[1], x[0]), filter(lambda x: x[1] > 0, enumerate(x))), key=lambda x: x[1], reverse=True)

In [95]:
pred_s6[0], pred_g11[0], ovas[0]

(array([ -7.1405587,  -6.112155 ,  -7.0942984,  -2.157643 , -11.490736 ,
          9.057835 ,  -5.695767 ,  -4.30681  , -10.373303 ,  -2.5170908],
       dtype=float32),
 array([-16.372932 , -13.989403 , -12.656205 ,  -0.1026834, -15.647539 ,
         14.554334 , -13.3617325,  -8.468777 , -20.558369 ,  -7.6444073],
       dtype=float32),
 array([-16.092613, -30.111294, -19.372639, -17.52673 , -20.258436,
         17.768173, -12.715565, -15.55067 , -22.144842, -16.646185],
       dtype=float32))

In [96]:
ans = np.argmax(np.max(np.dstack([pred_s6, pred_g11, ovas]), axis=-1), axis=-1)

In [97]:
ans

array([5, 4, 1, ..., 0, 9, 2], dtype=int64)

In [98]:
ensemble_model_name = 'ensemble_g_7_sem5_test'
ans = pd.DataFrame({'Id': np.arange(ans.shape[0]), 'Category': ans})
ans.to_csv(f'../answers/{ensemble_model_name}.csv', index=False)